version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfiles/worker/Dockerfile
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "${WORKER_PORT}:8000"
    depends_on:
      - mysql
    environment:
      - APP_ENV=dev

  mysql:
    build:
      context: .
      dockerfile: Dockerfiles/mysql/Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"

  swagger:
    build:
      context: .
      dockerfile: Dockerfiles/swagger/Dockerfile
    ports:
      - "${SWAGGER_PORT}:80"
    environment:
      SWAGGER_JSON: /swagger.yaml

volumes:
  mysql_data: